### PR TITLE
Add More Documentation

### PR DESCRIPTION
**Pull request by ItWasEnder**
Add solution to an issue on windows when certain C++ libraries are not installed while compiling VSCode.

### CODE REVIEW

**Comment by nang-dev** [comment]
Failed formatting 

also can we move common issues to another md? I think it clutters the readme 

thanks for the add tho ender!!!

**Review by nang-dev — COMMENTED** [review]
see comment

**Comment by nang-dev** [comment]
Github force closed this upon refactor :(

**Comment by ItWasEnder** [comment]
> Github force closed this upon refactor :(

I'll be adding this later, was very busy today.

**Pull request closed without merging**
