### PR TITLE
Updated visuals on the new window page

### PR DESCRIPTION
**Pull request by MaxFSP**
Solves #104 

image

image

### CODE REVIEW

**Comment by Fryingpannn** [comment]
Rip @nang-dev cooked your PR 🤣

**Comment by MaxFSP** [comment]
> Rip @nang-dev cooked your PR 🤣

Lol now what, do i just pull the latest changes and make a new pr? or do i deal with the awful merge process

**Comment by nang-dev** [comment]
i can fix

**Comment by nang-dev** [comment]
fixed :D

**Comment by nang-dev** [comment]
tysm max!

**Pull request merged**
