### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by gsewsankar**
18.19.x is the max Node version

>=18.20.x says 
Installing node-gyp failed

### CODE REVIEW

**Comment by cqdev-co** [comment]
Node: v18.19.0
Python: Python 3.12.3
yarn: 1.22.22
GIT: git version 2.30.0.windows.2
image

**Review by cqdev-co — APPROVED** [review]
lgtm

**Review by Fryingpannn — COMMENTED** [review]
Hmm my node version is `v18.20.2` and mine works. At which moment do you get that node-gyp error? Perhaps we should simply add in Common Errors, that if one gets the node gyp error, to downgrade node version.
Screenshot 2024-05-29 at 2 11 10 AM

**Comment by nang-dev** [comment]
Ty but outdated now, we upgraded to use node v20

**Pull request closed without merging**
