### PR TITLE
Fixing CI for macOS run

### PR DESCRIPTION
**Pull request by cqdev-co**
Running the script ./setup-environment.sh on the macOS side will always fail due to main and the current branch having different files. 

Commented it out for now when I have some time to address it but won't cause any problems

### CODE REVIEW

**Comment by MaySoMusician** [comment]
trying to review
meanwhile, could you resolve the conflict?

**Review by MaySoMusician — CHANGES_REQUESTED** [review]
need resolving the conflicts

**Comment by nang-dev** [comment]
yessir this is nice. can we also remove the submodule hash bump from this PR?

**Review by nang-dev — CHANGES_REQUESTED** [review]
commented

**Review by MaySoMusician — DISMISSED** [review]
Now can we proceed?

**Comment by cqdev-co** [comment]
It should be fine @MaySoMusician , I see that the submodule is included- is that going to be a problem?

**Comment by MaySoMusician** [comment]
@nang-dev could you resolve conflicts again and approve this?

**Comment by nang-dev** [comment]
fixed the submodule. the diff is still there but i changed it to point to the correct hash. the submodule is same as main now.

**Comment by nang-dev** [comment]
hm i wonder why its still failing here #159

**Pull request merged**
