### PR TITLE
Allow Pear to build on Windows

### PR DESCRIPTION
**Pull request by gedeondoescode**
This PR is intended for building Pear AI on Windows with the new submodule forked from Continue. Right now, this doesn't work as intended as the Webview does not load at all. But the extension can be built and added to the main app.

This will remain a draft until I figure out a way to get the Webview up and running again.

### CODE REVIEW

**Review by gedeondoescode — COMMENTED** [review]
An important note to make of this is that this will only work with my branch in [pearai-submodule](https://github.com/trypear/pearai-submodule/pull/40) as I have made some significant changes to the submodule that are not yet on main.

**Comment by gedeondoescode** [comment]
Windows support apparently works now 
image

**Review by ItWasEnder — APPROVED** [review]
LGTM. Send to prod.

Using their `sub-module` branch and running the `setup-environment` on windows after which manually running `scripts/code` from the terminal and **NOT** the VS Code actions launches the OSS window.

There are a lot of issues with running scripts through the editor at the moment, so we should make it known to only manually run scripts via terminal @nang-dev

**Comment by nang-dev** [comment]
True agreed thanks ender and gedeon

**Review by Fryingpannn — APPROVED** [review]

**Pull request merged**
