### PR TITLE
Update submodule GitHub action 

### LINKED ISSUE #128: Create a job that runs every night to update the extensions/pearai-submodule to main sha hash

### PR DESCRIPTION
**Pull request by benleembruggen**
- Fixes #128
- Adds GitHub action to update the `extensions/pearai-submodule` to main sha hash
- Automatically runs every night at midnight
- Added timeout incase it hangs

### CODE REVIEW

**Comment by nang-dev** [comment]
Yo! thanks for the pr

**Comment by nang-dev** [comment]
wondering if this works bc it might be in the git ignore?

**Comment by nang-dev** [comment]
is this tested by chance?

**Comment by benleembruggen** [comment]
@nang-dev Not sure how to test the action locally, however when I run the commands I get the following diff in the `pearai-app` repo:
```
diff --git a/extensions/pearai-submodule b/extensions/pearai-submodule
index d40eb4b2cc4..1c9522c69bf 160000
--- a/extensions/pearai-submodule
+++ b/extensions/pearai-submodule
@@ -1 +1 @@
-Subproject commit d40eb4b2cc4fc67a47d6ff77df70f7d1deb71926
+Subproject commit 1c9522c69bf22e8978074c921e723e9351ae1001
```
I can stage and commit these changes from the `pearai-app` repo, these changes are not being ignored by the `.gitignore` (which is what we need)

**Comment by cqdev-co** [comment]
Run a workflow dispatch to confirm that the GA works, once the run is confirmed then it will be merged

**Review by cqdev-co — CHANGES_REQUESTED** [review]
Looks good, left a action comment before merging

**Comment by benleembruggen** [comment]
@cqdev-co Looks like first time contributors can't run actions from a forked repo.

> To help prevent this, workflows on pull requests to public repositories from some outside contributors will not run automatically, and might need to be approved first. By default, all first-time contributors require approval to run workflows.

(https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks)

Instructions are provided [here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork) on how to approve actions from a public fork.

cc: @nang-dev

**Comment by cqdev-co** [comment]
I don't see any requests for actions to run @benleembruggen

**Comment by benleembruggen** [comment]
@cqdev-co Maybe because it's triggered by a schedule and not on a PR open or master merge. Not sure why it's not showing on your end

**Review by nang-dev — APPROVED** [review]
down to monitor this

**Comment by benleembruggen** [comment]
@nang-dev It looks like the workflow failed as the `github-actions@github.com` does not have permission to push to a protected branch. We should probably create a Github App for the organization (which will have permission to push to a protected branch), and use this inside action workflows, [this seems to fix](https://github.com/orgs/community/discussions/25305#discussioncomment-8256560) the problem for others.

I don't think that I would be able to test this on my forked repo, someone with access to this repo will need to configure this.

**Pull request merged**
