### PR TITLE
Implement code referencing when opening chat (#19) (WIP)

### PR DESCRIPTION
**Pull request by ItWasEnder**
**CURRENTLY WIP**

The goals are to be able to select code and have it contextualized to the next user question.
This PR is based on issue #19 

### Todo
- [x] Send code selection to new conversation
- [ ] Code view should reflect current VSCode theming
- [ ] Be able to remove code snippet from message

### Bonus
- [ ] Shortcut to load more code snippets to message context
- [ ] Implement along side #44 , similarly to cursor code referencing

### Ideas
- Use manaco editor as a read-only viewer for code/context snippets
- Use vscode css variables to set token highlighting colors
- Use styled markdown instead of editor (this should simplify implementation)

### CODE REVIEW

**Comment by conorquinlan65** [comment]
Take a look at why it's failing the lint test

**Comment by gedeondoescode** [comment]
Something is definitely weird about these actions. Perhaps @nang-dev could take a look at it and see what's up as this now the second PR failing lint checks.

**Comment by nang-dev** [comment]
Yiiiiikes my bad. taking a look

**Comment by gedeondoescode** [comment]
Lint check seems to be working now. Just make sure to run `yarn prettier` before setting this PR up for review.

**Comment by Fryingpannn** [comment]
goated PR but closing due to new submodule

**Pull request closed without merging**
