### PR TITLE
build Pear AI on windows

### PR DESCRIPTION
**Pull request by gedeondoescode**
Currently, the extension doesn't build and execute with `./scripts/code.bat`. This aims to fix that and potentially fix any issues relating to #17

### CODE REVIEW

**Comment by nang-dev** [comment]
did this make it work on windows?

**Comment by gedeondoescode** [comment]
> did this make it work on windows?

waiting on other Windows users

**Review by ItWasEnder — APPROVED** [review]
LGTM

**Comment by gedeondoescode** [comment]
Runs fine on other Windows machines. Thanks, @ItWasEnder !

**Comment by nang-dev** [comment]
BIGGG

**Pull request merged**
